# Centralized config for payment-service
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:Janu@0307}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:pharmacy_super_secret_key_for_hs256_min_32chars}
